feat: finished sentencizer first version
jina-ai/executor-text-sentencizer pull request #1
Opened 2021-07-14 11:24 UTC by jakob1111996

2021-07-15 08:44 UTC, nan-wang requested changes
minor change needed. LGTM

2021-07-15 08:44 UTC, nan-wang commented on manifest.yml
> +keywords: [text, sentence, split]
```suggestion
keywords: [text, sentencizer]
```

2021-07-15 13:06 UTC, Yongxuanzhang commented on setup.py
> +    package_dir={'jinahub.text': '.'},
This should follw 
jinahub.[indexer|encoder|segmenter|ranker|].module_name
so I think we should use segmenter?

2021-07-17 14:43 UTC, nan-wang approved these changes
LGTM👍

2021-07-17 14:43 UTC, merged